version: "3.8"

volumes:
  miniflux-db:
    name: miniflux-pgdb
    external: true
  
networks:
  proxy-network:
    external: true

services: 
  miniflux:
    image: miniflux/miniflux:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - default
      - proxy-network
    env_file:
      - miniflux.env
    environment:
      - CREATE_ADMIN
      - ADMIN_USERNAME
      - ADMIN_PASSWORD
    healthcheck:
      test: ["CMD", "/usr/bin/miniflux", "-healthcheck", "auto"]
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - miniflux-db:/var/lib/postgresql/data
    networks:
      - default
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
