volumes:
  miniflux-db:
    name: miniflux-pgdb
    external: true

networks:
  proxy-network:
    external: true

services:
  miniflux:
    image: miniflux/miniflux:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - default
      - proxy-network
    env_file:
      - miniflux.env
      - path: ./miniflux-initial.env
        required: false
    healthcheck:
      test: ["CMD", "/usr/bin/miniflux", "-healthcheck", "auto"]
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - miniflux-db:/var/lib/postgresql/data
    networks:
      - default
    env_file:
      - path: ./miniflux-initial.env
        required: false
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
