# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/

volumes:
  data:
    name: pihole-data
    external: true
  dnsmasq:
    name: pihole-dnsmasq
    external: true

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - 53:53/udp
      - 53:53/tcp
      - 81:80
    environment:
      - TZ=Europe/Berlin
      - WEBPASSWORD
    volumes:
      - data:/etc/pihole
      - dnsmasq:/etc/dnsmasq.d
      - ./90-reverse-ipv6.conf:/etc/dnsmasq.d/90-reverse-ipv6.conf
